### ISSUE TITLE
Typo: cusor instead of cursor

### ISSUE THREAD

**Issue by corecache** [gbiobob/ED3D-Galaxy-Map#10]
Hi there,

There is a consistent typo with "cusor" instead of "cursor" - "r" is missing:

`# grep -ir cusor js/components/`

`js/components/action.class.js:    this.addCusorOnHover(sel.x, sel.y, sel.z);`
`js/components/action.class.js:    this.addCusorOnSelect(goX, goY, goZ);`
`js/components/action.class.js:  'addCusorOnSelect' : function (x, y, z) {`
`js/components/action.class.js:  'addCusorOnHover' : function (x, y, z) {`

**Comment by gbiobob** [comment]
Thanks!
I just fix that ;)
