### ISSUE TITLE
Display System names by default

### ISSUE THREAD

**Issue by corecache** [gbiobob/ED3D-Galaxy-Map#11]
It would be nice if there was an option to display system names by default instead of having to click

More technically: where would you add code to make that one work? Maybe I give it a look

**Comment by gbiobob** [comment]
Done, now I show object name on hover by default ;)
I just add two lines of code, already got a method to add text on object: HUD.addText(...)

**Comment by corecache** [comment]
Showing the names on-hover is good indeed, but I was also rather looking for a global option to set upon init to show/hide all system names by default in a certain range of the camera

**Comment by gbiobob** [comment]
ok I understand, I fear about performances for something like that, 
actually there is only one single text object, I just move/change it according to mouse position.
 As example on a map with all EDSM systems, if I show all systems names in a range around the camera, it will probably kill the app :) (huge system density).
I will try to made a test this evening, I could start with an option to show the 20-30 most close systems from the camera instead of using a range.

**Comment by corecache** [comment]
If you look at how Frontier circumvented the same problem in their galaxy map, you'll see that they have a bubble around the camera in which stuff is beeing display - if you leave that bubble, stuff gets flattened out.

Indeed the app is going to explode for databases such as EDSM - maybe stop displaying names/sprites at a certain distance X to the horizontal plane - routes on the other hand should still be visible from far outside.

**Comment by AnthorNet** [comment]
The main concern is that the performance on WebGL aren't really the same as they are for a compiled application, doing the exact same things as they did in the game would be really performance killer

**Comment by gbiobob** [comment]
I just release a new option to show systems name near from camera, just set the "showNameNear" to true to test it ;) (I've add activate option in the demo_galnet.html)
At this time it's very experimental and should not kill the browser (not yet fully optimized),
it will show all names close to the camera with a limit of 50 systems to avoid issues on huge systems density. For performances I refresh names only every 1 second (less could cause lags).

**Comment by gbiobob** [comment]
As no feedback & work well on my side,
Close.
