### ISSUE TITLE
Issue on texture loading on last Chrome release (r50)

### ISSUE THREAD

**Issue by gbiobob** [gbiobob/ED3D-Galaxy-Map#12]

**Comment by AnthorNet** [comment]
Damn I spend hours trying to figure out this :D

**Comment by gbiobob** [comment]
The issue is on the img.onload, apparently last r50 Chrome doesn't fire the event.
The main discuss about that on Three.js: https://github.com/mrdoob/three.js/issues/8670
Apparently, we should wait for a fix from Google.

**Comment by gbiobob** [comment]
Test on Chrome dev channel (r52), everything work well.

**Comment by gbiobob** [comment]
Last Chrome stable release fix the issue.
