### ISSUE TITLE
Licence?

### ISSUE THREAD

**Issue by purrcat259** [gbiobob/ED3D-Galaxy-Map#22]
Hi there,

I'm interested in forking / basing off your project. Can you put down a licence file so that I can know what I should be doing when considering whether I have to keep it open source, release contributions, etc?

Thanks!

**Comment by gbiobob** [comment]
Hi,
it's done!
please let me know when you will have something to show, I'm always curious to see new use case of the map :)

**Comment by simonamdev** [comment]
Thanks for the quick resolution, I'll close this issue then :)

The aim is to use it in combination with my own project [EDJP](https://github.com/purrcat259/elite-dangerous-journal-pipeline) to visualise tracked minor faction movement and influence in real time. I asked for the licence as it is unclear so far how much of my fork/own version will be open.

**Comment by gbiobob** [comment]
Nice!

you can find me on the EDCD discord server if needed.
