### ISSUE TITLE
Suggestion - Add progress bar while loading huge JSON

### ISSUE THREAD

**Issue by Gerdofal** [gbiobob/ED3D-Galaxy-Map#5]
It would be great if we could have a progress bar, or even a spinning wheel and a loading message, while loading a huge JSON. That edsm.json I make every night takes even a good browser on a good connection a while to load it. (Delay only noticeable on first visit to the page each day.)

**Comment by gbiobob** [comment]
I will add that this week-end (I'm away for a few days)

**Comment by gbiobob** [comment]
Hi!
I've improve the loader for huge JSON files, now there message for each loading step + a small anim when a step take too much time.

**Comment by Gerdofal** [comment]
Awesome. Looks great!
