### ISSUE TITLE
Minor camera issue - camera moves when categories clicked

### ISSUE THREAD

**Issue by Gerdofal** [gbiobob/ED3D-Galaxy-Map#6]
The camera resets to the start when categories are clicked. You can see what I mean here:

http://gerdofal.net/ed/ed3dmap/plotedsm.php

Manually move the camera, then click a category, the camera will move back to a reset position.

**Comment by gbiobob** [comment]
Clicking on a category move back the camera position to initial position,
I just made an upgrade about that:
now clicking (1.2.1 release) on a group will center the camera on center of the group, the camera distance should be also dynamic.
I'm curious to see how it will work on your map :)

**Comment by Gerdofal** [comment]
From what I can see, this works nicely on both of my maps:

http://gerdofal.net/ed/ed3dmap/plotedsm.php

and the routing map generated when you get a new route from here:

http://gerdofal.net/ed/1krouting.php
