### ISSUE TITLE
Error after updating to newest version

### ISSUE THREAD

**Issue by Gerdofal** [gbiobob/ED3D-Galaxy-Map#8]
Pages fail to load after update to newest version. Error is:

Uncaught TypeError: THREE.Spherical is not a constructor

**Comment by Gerdofal** [comment]
Maybe I need to change something in the page I'm calling from?

**Comment by Gerdofal** [comment]
Found it, the script call from your example code didn't change from r73 to r75 :)

**Comment by AnthorNet** [comment]
I assume you found three is last revision ;)
